# Generated by Django 3.2.9 on 2021-11-11 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUpdateNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('intro', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 11, 11, 14, 23, 55, 632732))),
            ],
        ),
    ]
