# Generated by Django 3.2.9 on 2021-11-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_auto_20211111_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteupdatenews',
            name='date',
            field=models.DateTimeField(default='November 11 2021 - 14:13:35'),
        ),
    ]
