# Generated by Django 3.2.9 on 2021-11-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_alter_siteupdatenews_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteupdatenews',
            name='date',
            field=models.DateTimeField(default='2021-11-11 14:17'),
        ),
    ]
