# Generated by Django 3.2.10 on 2021-12-09 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeapp', '0006_alter_siteupdatenews_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteupdatenews',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_updatenews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='siteupdatenews',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='UserUpdateNewsRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 'Bad'), (2, 'Not Bad'), (3, 'Ok'), (4, 'Fine'), (5, 'Amazing')], null=True)),
                ('update_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.siteupdatenews')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='siteupdatenews',
            name='watchers',
            field=models.ManyToManyField(related_name='updatenews_watchers', through='homeapp.UserUpdateNewsRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
